---
title: "Fractions continues"
author: "Vincent Cognet"
date: "27/12/2019"
output:
  
  html_document:
    df_print: paged
  always_allow_html: true
  word_document: default
  pdf_document: default
---




$$
\sqrt{2} = 1+\sqrt{2} -1 
= 1+ \frac{(\sqrt{2} -1)(\sqrt{2} +1)}{\sqrt{2} +1} 
= 1 + \frac{1}{1+\sqrt{2}}
$$

\begin{equation}
  \sqrt{2} = 1 + \cfrac{1}{2 
          + \cfrac{1}{2 
          + \cfrac{1}{2 
          + \cfrac{1}{2
          + \cfrac{1}{2
          + \cfrac{1}{...
          } } } }}}
\end{equation}


```{r implementation}
racine2 <- function(n=1, limit=20) {
  if (n==limit) {return(1)} 
  else
  {
    return(1+(1/(1+racine2(n+1, limit))))
  }
}

options(digits = 20)
print("la valeur de racine 2"); print (2^(1/2))
print("l'approximation par la fraction continue"); print(racine2())

```

```{r haskell, engine="haskell", engine.path="C:/Program Files/Haskell Platform/8.6.5/bin/runghc.exe", include = TRUE}


module Main where
import Prelude
racine2 n 
 | n==1 = 1 
 | otherwise = 1 + 1 / (1 + racine2 (n-1))
main = print (racine2 20)

```


```{r}
racine2latex <- function(n=1, limit=20) {
  if (n==limit) {return("...")}
  else
  {
    return(c("\\cfrac{1}{2+", racine2latex(n+1, limit), "}" ))
  }
}
cat(c("\\sqrt{2} = 1 +", racine2latex()))
```


cat("\\sqrt{2} = 1 +", racine2latex())

$$
\sqrt{2} = 1 + \cfrac{1}{2+ \cfrac{1}{2+ \cfrac{1}{2+ \cfrac{1}{2+ \cfrac{1}{2+ \cfrac{1}{2+ \cfrac{1}{2+ \cfrac{1}{2+ \cfrac{1}{2+ \cfrac{1}{2+ \cfrac{1}{2+ \cfrac{1}{2+ \cfrac{1}{2+ \cfrac{1}{2+ \cfrac{1}{2+ \cfrac{1}{2+ \cfrac{1}{2+ \cfrac{1}{2+ \cfrac{1}{2+ ... } } } } } } } } } } } } } } } } } } }
$$
```{r output=FALSE}
eu <- function(a, b) {
   euclide <- matrix(ncol=4, nrow=10)
   colnames(euclide) <- c("a", "b", "q", "r")
   euclide[1,"a"] <- a
   euclide[1,"b"] <- b
   euclide[1,"q"] <- a%/%b
   euclide[1,"r"] <- a%%b
   i <- 1
   while (euclide[i, "r"]!=0)
     {
   i <- i+1
   euclide[i, "a"] <- euclide[i-1,"b"]
   euclide[i, "b"] <- euclide[i-1,"r"]
   euclide[i, "q"] <- euclide[i,"a"] %/% euclide[i,"b"]
   euclide[i, "r"] <- euclide[i,"a"] %% euclide[i,"b"]
   }
   
   output <- c("\\frac{", a, "}{", b , "}=")
   i <- 1
   while (euclide[i, "r"]!=0)
    {
     output <- c(output, euclide[i, "q"], "+\\cfrac{1}{" )
     i <- i+1
    }
   output <- c(output, euclide[i, "q"] )
   for (j in (1:(i-1)))
   { output <- c(output, "}") 
   }
   
   print(euclide)
   cat(output)
 
}

eu(840,611)
```



$$\frac{ 840 }{ 611 }= 1 +\cfrac{1}{ 2 +\cfrac{1}{ 1 +\cfrac{1}{ 2 +\cfrac{1}{ 76 } } } } $$

```{r}
eu(11,8)
```
$$\frac{ 11 }{ 8 }= 1 +\cfrac{1}{ 2 +\cfrac{1}{ 1 +\cfrac{1}{ 2 } } }$$
```{r}
eu(15625,6842)
```

$$\frac{ 15625 }{ 6842 }= 2 +\cfrac{1}{ 3 +\cfrac{1}{ 1 +\cfrac{1}{ 1 +\cfrac{1}{ 9 +\cfrac{1}{ 1 +\cfrac{1}{ 1 +\cfrac{1}{ 48 } } } } } } }$$
 
## La suite de Fibonacci et le nombre $\Phi$
 
 
```{r output=FALSE}
fib <- function(n) {
   if ((n==1) | (n==2)) {return(1)}
   else return(fib(n-1)+fib(n-2))
}

fiblist <- function(n) {
   if ((n==1) | (n==2)) {return(list(1))}
   else return(list(fiblist(n-1), fiblist(n-2)))
}


fib_terminal <- function(n, a=1, b=0) {
  if (n==1) {
    return(a+b) 
    }
  else {
    return(fib_terminal(n-1, b, a+b))
  }
}

fib_terminal_list <- function(n, a=1, b=0) {
  if (n==1) {
    return(list(a+b))
    }
  else {
    return(list(fib_terminal(n-1, b, a+b)))
  }
}

memo <- vector(length = 100)
memo[1] <- 1
memo[2] <- 1

fib_memo <- function(n, v) {
  if (v[n]!=0) {
      return(v[n])
      }
    else {    
    v[n] <- fib_memo(n-1, v) + fib_memo(n-2, v)
     }
  return(v[n])
  }


library(data.tree)
library(DiagrammeR)

arbre_fib <- as.Node(fiblist(8))

fib_recalculate <- function(n) {
   if (n$isLeaf == TRUE) {
      n$value <- 1
   }
  else 
   {
     if (n$count==2) {
       n$value <- n$children[[1]]$value + n$children[[2]]$value 
    }
     else {
        n$value <- n$children[[1]]$value +1 
     }
   }
}
 

fib_decorate <- function(node, n) {
  if (node$count == 0) {
    node$nom <-  paste("fib(", n ,")=", node$value, sep="")
    return(node)
  }
  else {
    if (node$count ==1) {
      node$nom <- paste("fib(", n ,")=", node$value, sep="")
      fib_decorate(node$children[[1]], n-1)
    }
      else {
        node$nom <-  paste("fib(", n ,")=", node$value, sep="")
        fib_decorate(node$children[[1]], n-1)
        fib_decorate(node$children[[2]], n-2)
      }
  }}
  
  
  arbre_fib$Do(fib_recalculate, traversal = "post-order")
  fib_decorate(arbre_fib, 8)
SetNodeStyle(arbre_fib,  label = function(x) x$nom)
plot(arbre_fib)
print(arbre_fib, "value", "nom")
```
```{r test-haskell, cache=TRUE, engine='haskell', engine.path="C:/Program Files/Haskell Platform/8.6.5/bin/ghc.exe",cache=TRUE}
main = do
       putStrLn "Greetings!  What is your name?"

```


